adding plnety functions

diff --git a/lemptool_scripts b/lemptool_scripts
--- a/lemptool_scripts
+++ b/lemptool_scripts
@@ -46,9 +46,11 @@ check_for_y(){
     fi
   done
 
+
   return $confirmation
 
 }
+
 
 
 
@@ -77,10 +79,6 @@ validate_php_version() {
 
 #---------------PHP INSTALL-------------------
 install_php() {
-  show_confirmations=1
-  if  ! check_for_y "$@"; then
-    show_confirmations=0
-  fi
 
   validate_sudo
   validate_php_version "$1"
@@ -162,10 +160,7 @@ install_php() {
 
 #---------------NGINX INSTALL-------------------
 install_nginx() {
-  show_confirmations=1
-  if  ! check_for_y "$@"; then
-    show_confirmations=0
-  fi
+
 
 
   validate_sudo
@@ -237,10 +232,6 @@ install_nginx() {
 #---------------MARIADB INSTALL-------------------
 install_mariadb() {
 
-  show_confirmations=1
-  if  ! check_for_y "$@"; then
-    show_confirmations=0
-  fi
 
 
   validate_sudo
@@ -303,11 +294,10 @@ install_mariadb() {
 
 }
 
+
+#---------------FPM CREATE-------------------
 fpm_create() {
-  show_confirmations=1
-  if  ! check_for_y "$@"; then
-    show_confirmations=0
-  fi
+
   validate_sudo
 
   validate_envsubst
@@ -386,12 +376,9 @@ fpm_create() {
 
 
 
-
+#---------------FPM NG CREATE -------------------
 fpm_ng_server_create(){
-  show_confirmations=1
-  if  ! check_for_y "$@"; then
-    show_confirmations=0
-  fi
+
   validate_sudo
   validate_envsubst
   validate_php
@@ -400,6 +387,14 @@ fpm_ng_server_create(){
   NG_SERVER_PATH=$3
   NG_SERVER_DOMAIN=$2
   NG_SERVER_FPM_NAME=$1
+
+
+
+  if [ -z "$NG_SERVER_DOMAIN" ]; then
+    echo "This script needs a domain to configure nginx sever"
+    echo "Please type a domainr"
+    read -r NG_SERVER_DOMAIN
+  fi
 
   if [ -z "$NG_SERVER_PATH" ]; then
     echo "This script needs a path to serve with a nginx server"
@@ -410,13 +405,6 @@ fpm_ng_server_create(){
       echo "$NG_SERVER_PATH directory does not exist."
       exit 1
   fi
-
-  if [ -z "$NG_SERVER_DOMAIN" ]; then
-    echo "This script needs a domain to configure nginx sever"
-    echo "Please type a domainr"
-    read -r NG_SERVER_DOMAIN
-  fi
-
 
   CURRENT_PHP_VERSION=$(php -v | grep PHP)
   CURRENT_PHP_VERSION=${CURRENT_PHP_VERSION:4:3}
@@ -461,14 +449,22 @@ fpm_ng_server_create(){
 
   AVAILABLE_SERVERS_PATH="/etc/nginx/sites-available"
   ENABLED_SERVERS_PATH="/etc/nginx/sites-enabled"
-  CURRENT_SERVER_FILE="$AVAILABLE_SERVERS_PATH/$NG_SERVER_DOMAIN.conf"
+  CURRENT_SERVER_FILE="$AVAILABLE_SERVERS_PATH/$NG_SERVER_DOMAIN"
+
+
+  if [  -f "$CURRENT_SERVER_FILE" ]; then
+    echo "Nginx server file $CURRENT_SERVER_FILE already exists, and it will not be overwriten"
+    exit 1
+  fi
+
+
   if !  envsubst < "templates/laravel/nginx/server/server_unit_template" > "$CURRENT_SERVER_FILE"; then
     echo "Error on nginx server unit file creation"
     exit 1
   fi
 
 
-  ln -s "$CURRENT_SERVER_FILE" "$ENABLED_SERVERS_PATH/$NG_SERVER_DOMAIN.conf";
+  ln -s "$CURRENT_SERVER_FILE" "$ENABLED_SERVERS_PATH/$NG_SERVER_DOMAIN";
 
   if ! nginx -t; then
     echo "Error on nginx server unit content"
@@ -483,6 +479,127 @@ fpm_ng_server_create(){
   echo "Nginx server successfully created"
 
 }
+
+
+#---------------LEMP CREATE-------------------
+lemp_create(){
+
+  validate_sudo
+  validate_php
+  validate_nginx
+
+  LEMP_USER=$1
+  LEMP_DOMAIN=$2
+  LEMP_DBUSER_PASSWORD=$3
+
+  if [ -z "$LEMP_DBUSER_PASSWORD" ]; then
+    echo "The password for db user param is mandatory"
+    exit 1
+  fi
+
+  if [ -z "$LEMP_DOMAIN" ]; then
+    echo "The domain param is mandatory"
+    exit 1
+  fi
+
+  if [ -z "$LEMP_USER" ]; then
+    echo "The os user param is mandatory"
+    exit 1
+  fi
+
+  str="$LEMP_DOMAIN"
+  oldstr="-"
+  newstr="_"
+  str=$(echo $str | sed "s/$oldstr/$newstr/g")
+  oldstr="."
+  newstr="_"
+  LEMP_DOMAIN_SCAPED=$(echo $str | sed "s/$oldstr/$newstr/g")
+
+
+
+
+
+}
+
+#---------------DB USER CREATE-------------------
+add_mdb_user(){
+  validate_sudo
+  validate_mariadb
+  MDB_USERNAME=""
+  MDB_PASSWORD=""
+  MDB_HOST="%"
+  if [ -z "$1" ]; then
+    echo "Please type the username to add"
+    read -r MDB_USERNAME
+  else
+    MDB_USERNAME="$1"
+  fi
+  if [ -z "$2" ]; then
+    echo "Please type the password for $MDB_USERNAME"
+    read -r MDB_PASSWORD
+  else
+    MDB_PASSWORD="$2"
+  fi
+  if [ -n "$3" ]; then
+
+    MDB_HOST="$3"
+  else
+    echo "You dint gave a hostname for this new user:  $MDB_USERNAME "
+    echo "User will be created with % as host."
+    if [ $show_confirmations -eq 1 ]; then
+      confirmation_message
+    else
+      echo "> message:"
+      echo "Confirmation avoided !"
+    fi
+    MDB_HOST="%"
+  fi
+
+  CREATE_USER_QUERY="CREATE USER IF NOT EXISTS '$MDB_USERNAME'@'$MDB_HOST' IDENTIFIED BY '$MDB_PASSWORD';"
+  if echo "$CREATE_USER_QUERY" | mysql ; then
+    echo "User $MDB_USERNAME @ $MDB_HOST created "
+    return 0
+  else
+    echo "Error creating user $MDB_USERNAME"
+    return 1
+  fi
+}
+
+add_mdb_superuser(){
+  if ! add_mdb_user "$@" ;then
+    echo "Super user can not be created"
+    exit
+  fi
+
+
+
+  CREATE_USER_QUERY="GRANT ALL PRIVILEGES ON *.* TO '$MDB_USERNAME'@'$MDB_HOST' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;FLUSH PRIVILEGES;"
+  if echo "$CREATE_USER_QUERY" | mysql ; then
+    echo "User $MDB_USERNAME @ $MDB_HOST is now SUPER USER "
+    return 0
+  else
+    echo "ERROR on giving all privileges to  $MDB_USERNAME @ $MDB_HOST "
+    return 1
+  fi
+}
+add_mdb_user_with_db(){
+  if ! add_mdb_user "$@" ;then
+    echo "Super user can not be created"
+    exit
+  fi
+
+
+  CREATE_USER_QUERY="GRANT USAGE ON *.* TO '$MDB_USERNAME'@'$MDB_HOST' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`; GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$MDB_USERNAME'@'$MDB_HOST'; "
+  echo CREATE_USER_QUERY
+  if echo "$CREATE_USER_QUERY" | mysql ; then
+    echo "User $MDB_USERNAME @ $MDB_HOST created with a database named $DB_NAME"
+    return 0
+  else
+    echo "Error creating user $MDB_USERNAME db "
+    return 1
+  fi
+}
+#---------------PHPMYADMIN INSTALL -------------------
 install_phpmyadmin() {
   validate_sudo
   echo ""
@@ -503,13 +620,11 @@ install_phpmyadmin() {
   echo "This script will install install phpMyAdmin $PHPMYADMIN_VERSION."
   echo "Also this script will create a phpmyadmin user if not exists, add a new phpmyadmin fpm for the phpmyadmin created user, later it will create a phpmyadmin nginx server."
   confirmation_message
-
   PHPMYADMIN_DOWNLOAD_URL="https://files.phpmyadmin.net/phpMyAdmin/$PHPMYADMIN_VERSION/phpMyAdmin-$PHPMYADMIN_VERSION-all-languages.zip"
   PHPMYADMIN_USER_PATH="/home/$PHPMYADMIN_USERNAME"
   PHPMYADMIN_DOWNLOAD_PATH="$PHPMYADMIN_USER_PATH/phpmyadmin.zip"
   PHPMYADMIN_EXTRACTION_PATH="$PHPMYADMIN_USER_PATH/phpMyAdmin-$PHPMYADMIN_VERSION-all-languages"
   PHPMYADMIN_PUBLIC_PATH="/opt/$PHPMYADMIN_USERNAME"
-
   packages_installer unzip zip
   echo ""
   echo "$PHPMYADMIN_USERNAME user is needed"
@@ -528,11 +643,6 @@ install_phpmyadmin() {
   cp "templates/phpmyadmin/config.inc.php" "$PHPMYADMIN_PUBLIC_PATH/config.inc.php"
   sudo chown -R phpmyadmin $PHPMYADMIN_PUBLIC_PATH
 
-  #CURRENT_PHP_VERSION=$(php -v | grep PHP)
-  #CURRENT_PHP_VERSION=${CURRENT_PHP_VERSION:4:3}
-  #PHP_FPM_PATH="/etc/php/$CURRENT_PHP_VERSION/fpm/pool.d"
-
-  #cp "templates/phpmyadmin/php/phpmyadmin.conf" "$PHP_FPM_PATH/$PHPMYADMIN_USERNAME.conf"
 
   fpm_create "$PHPMYADMIN_USERNAME"
 
@@ -593,84 +703,5 @@ install_phpmyadmin() {
   fi
   echo "Nginx Service restarted !"
   echo "Bash phpmyadmin installation script end"
-
-}
-
-add_mdb_superuser(){
-  validate_sudo
-  validate_mariadb
-
-
-  MDB_USERNAME=""
-  MDB_PASSWORD=""
-  MDB_HOST="%"
-  if [ -z "$1" ]; then
-    echo "Please type the username to add"
-    read -r MDB_USERNAME
-  else
-    MDB_USERNAME="$1"
-  fi
-
-  if [ -z "$2" ]; then
-    echo "Please type the password for $MDB_USERNAME"
-    read -r MDB_PASSWORD
-  else
-    MDB_PASSWORD="$2"
-  fi
-
-  if [ -n "$3" ]; then
-    MDB_HOST="$3"
-  fi
-
-
-
-  #CREATE_USER_QUERY="CREATE USER '$MDB_USERNAME'@'%' IDENTIFIED  BY '$MDB_PASSWORD';GRANT USAGE ON *.* TO '$MDB_USERNAME'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS $MDB_USERNAME; GRANT ALL PRIVILEGES ON $MDB_USERNAME.* TO '$MDB_USERNAME'@'%'; "
-  CREATE_USER_QUERY="CREATE USER IF NOT EXISTS '$MDB_USERNAME'@'%' IDENTIFIED BY '$MDB_PASSWORD';GRANT ALL PRIVILEGES ON *.* TO '$MDB_USERNAME'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;FLUSH PRIVILEGES;"
-  if echo "$CREATE_USER_QUERY" | mysql ; then
-    echo "SUPER User $MDB_USERNAME @ $MDB_HOST created "
-    return 0
-  else
-    echo "Error creating user $MDB_USERNAME"
-    return 1
-  fi
-
-}
-add_mdb_user_with_db(){
-
-  validate_sudo
-  validate_mariadb
-
-
-  MDB_USERNAME=""
-  MDB_PASSWORD=""
-  MDB_HOST="%"
-  if [ -z "$1" ]; then
-    echo "Please type the username to add"
-    read -r MDB_USERNAME
-  else
-    MDB_USERNAME="$1"
-  fi
-
-  if [ -z "$2" ]; then
-    echo "Please type the password for $MDB_USERNAME"
-    read -r MDB_PASSWORD
-  else
-    MDB_PASSWORD="$2"
-  fi
-
-  if [ -n "$3" ]; then
-    MDB_HOST="$3"
-  fi
-
-
-
-  CREATE_USER_QUERY="CREATE USER '$MDB_USERNAME'@'%' IDENTIFIED  BY '$MDB_PASSWORD';GRANT USAGE ON *.* TO '$MDB_USERNAME'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS $MDB_USERNAME; GRANT ALL PRIVILEGES ON $MDB_USERNAME.* TO '$MDB_USERNAME'@'%'; "
-  if echo "$CREATE_USER_QUERY" | mysql ; then
-    echo "User $MDB_USERNAME @ $MDB_HOST created with a database named $MDB_USERNAME"
-    return 0
-  else
-    echo "Error creating user $MDB_USERNAME"
-    return 1
-  fi
 
 }
